kind: pipeline
type: docker
name: default

steps:
- name: Testing
  image: golang:1.20-alpine
  commands:
    - "cd ./src && go build"
    - "go test -v"
    - "go test ../test -v"

- name: Build
  image: docker
  commands:
    - docker build -t my-golang-app .
    - docker run -d -p 8080:8080 my-golang-app
  volumes:
    - name: dockersock
      path: /var/run