kind: pipeline
type: docker
name: prodcution

steps:
- name: greeting
  image: golang:1.20-alpine
  commands:
    - "go build"
    - "go test ./src"
    - "go test ./test"
  when:
    event: [ push ]
    branch: [ main ]