kind: pipeline
type: docker
name: default

steps:
- name: Testing
  image: golang:1.20-alpine
  commands:
    - "cd ./src && go build"
    - "go test -v"
    - "go test ../test -v"

- name: build
  image: plugins/docker
  commands:
    - docker build -t my-golang-app .

- name: run
  image: plugins/docker
  commands:
    - docker run -d -p 8080:8080 my-golang-app